# Generated by Django 4.0 on 2021-12-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(max_length=100)),
                ('contactor', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('storage_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('storage_name', models.CharField(max_length=100)),
                ('storage_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_size', models.CharField(max_length=100)),
                ('product_value', models.IntegerField(default=0)),
                ('product_leastcount', models.IntegerField(default=0)),
                ('product_maxcount', models.IntegerField(default=0)),
                ('product_storage', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='manage_system.storage')),
            ],
        ),
    ]
