# Generated by Django 4.0 on 2022-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_system', '0002_sys_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sys_users',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sys_users',
            name='user_authority',
            field=models.IntegerField(default=0),
        ),
    ]
